name: Unit Testing
on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.nim"
      - "listen2gether.nimble"

  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: version-1-6-5

      - name: Install
        run: nimble install -d:js -y

      - name: Run tests
        env:
          LISTENBRAINZ_USER: ${{ secrets.LISTENBRAINZ_USER }}
          LASTFM_USER: ${{ secrets.LASTFM_USER }}
        run: nimble test -d:c -y
