name: Web Deployment
on:
  push:
    tags:
       - '*'

  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: version-1-7

      - name: Setup Dart Sass, UglifyJS, html-minifer
        run: npm install -g sass uglify-js html-minifier

      - name: Install
        run: nimble install -d:js -y

      - name: Compile Sass
        run: nimble sass

      - name: Compile JS
        run: nimble buildjs

      - name: Minify
        run: nimble minify

      - name: Create /mirror path
        run: nimble prep

      - name: Generate docs
        run: nimble docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public
